services:
  pathless-demo:
    image: timefactory/pathless
    container_name: pathless-demo
    restart: unless-stopped
    pull_policy: always
    ports:
      - 127.0.0.1:1000:1000
    networks:
      - timefactory

  frame-demo:
    image: timefactory/demo:dev
    container_name: frame-demo
    restart: unless-stopped
    pull_policy: always
    ports:
      - 127.0.0.1:1001:1001
    networks:
      - timefactory
    volumes:
      - ./img:/img
      - ./slides:/slides
      - ./README.md:/README.md

networks:
  timefactory:
    driver: bridge
