services:
  pathless-demo:
    image: timefactory/pathless:dev
    container_name: pathless-demo
    restart: unless-stopped
    pull_policy: always
    ports:
      - 127.0.0.1:1000:1000

  frame-demo:
    image: timefactory/demo:dev
    container_name: frame-demo
    restart: unless-stopped
    pull_policy: always
    ports:
      - 127.0.0.1:1001:1001
    volumes:
      - ./one:/
    environment:
      - logo=/logo.svg
      - heading=the perpetual motion machine
      - slides=/slides
      - text=https://raw.githubusercontent.com/timefactoryio/pathless/refs/heads/main/README.md
