services:
  pathless-demo:
    image: timefactory/pathless
    container_name: pathless-demo
    restart: unless-stopped
    networks:
      - timefactory

  frame-demo:
    image: timefactory/demo
    container_name: frame-demo
    restart: unless-stopped
    networks:
      - timefactory

networks:
  timefactory:
    driver: bridge
