services:
  pathless-demo:
    image: timefactory/pathless
    container_name: pathless-demo
    restart: unless-stopped
    ports:
      - 127.0.0.1:1000:1000
    environment:
      - API_URL=http://frame-demo:1001
    networks:
      - timefactory

  frame-demo:
    image: timefactory/demo
    container_name: frame-demo
    restart: unless-stopped
    environment:
      - API_URL=http://frame-demo:1001
    networks:
      - timefactory

networks:
  timefactory:
    driver: bridge
